Update README
candlepin/packer pull request #1
Opened 2018-08-24 15:54 UTC by kahowell

2018-08-27 15:01 UTC, jirihnidek requested changes
I'm getting following error, when I try to run packer:

```console
[jiri@localhost packer]$ /home/jiri/software/vagrant/packer build -force subman-centos7.json
qemu output will be in this color.

1 error(s) occurred:

* access_token must be set
```

User has to have valid Vagrant account and user has to create token and environment variable `VAGRANT_CLOUD_TOKEN` has to contain value of this token.

2018-08-27 15:01 UTC, jirihnidek commented on README.md
> +packer build -force subman-centos7.json  # or other json files in this repo.
Don't forget to add note that this `packer` should be installed from: https://www.packer.io/. BTW: The name of this binary (`packer`) is not wise, because most of Linux systems contain packer from package cracklib-dist (it is probably used for searching for weak passwords). So, I guess that you did not install it to system (e.g. `/usr/local/bin`), but you have it in somewhere like `/home/user/soft/hashicorp/packer`.

2018-11-05 18:58 UTC, kahowell commented
@jirihnidek please take a look. I've pushed updates to the README.

2018-11-06 08:27 UTC, jirihnidek approved these changes
ACK

2018-11-06 08:27 UTC, merged